NSLS-II/filestore

.gitignore
.travis.yml
fileStore/__init__.py
fileStore/api/collection.py
fileStore/database/databaseInit.py
fileStore/database/mongoCollections.py
fileStore/file_readers.py
fileStore/retrieve.py
fileStore/tests/test_retrieve.py
run_tests.py
setup.py

This does a bunch of stuff, lets talk about this before it gets merged
- adds skeleton of the API to be exposed to dataBroker
- some minor house keeping
- moved the dictionary keys to package-level 'constants' so that it is easier to keep track of them across modules
- added testing framework

Retrive draft

---

.travis.yml
fileStore/__init__.py
fileStore/commands.py
fileStore/database/file_base.py
fileStore/database/file_event_link.py
fileStore/retrieve.py
fileStore/test/t_utils.py
fileStore/test/test_commands.py
fileStore/test/test_retrive.py
run_tests.py
setup.py

@arkilic ~~Don't merge this yet.~~
I still want to get tests for commands written and get travis set up.

Mongoengine refactor retrive

---

setup.py

Fixing missing import. Self-merging with @ericdill over my shoulder.

Add the fileStore.api package.

---

filestore/api.py

API: Add register_handler with the API.

---

filestore/commands.py
filestore/test/test_commands.py

MNT/TST : add disconnect + simplify tests

---

filestore/api.py
filestore/commands.py

still needs documentation on both functions

MNT/API : expose symmetric db_{connect,disconnect}

---

filestore/file_readers.py
filestore/handlers.py
filestore/test/test_handlers.py
filestore/test/test_reader.py
filestore/test/test_write.py

API: Minor tweaks

---

filestore/utils/testing.py

TST : add prefix to testing db name

---

.travis.yml
filestore/handlers.py
filestore/retrieve.py
filestore/test/test_handlers.py

- frame-wise .npy handler
- basic caching of handler

Enh npy framewise handler

---

filestore/commands.py
filestore/retrieve.py
filestore/test/test_commands.py

Completely untested!
attn @klauer

ENH: add bulk insert

---

filestore/fs.py

This was causing horendously bad performance with large numbers of datum

FIX/PRF: ensure index on 'resource' in datum col

---

filestore/conf.py

same fix as I submitted to MDS recently

FIX: Cast port ENV var to int.

---

.gitignore
filestore/handlers.py
filestore/test/test_handlers.py

This is a WIP (DO NOT MERGE) to add SWMR functionality.

Add SWMR functionality to filestore for AreaDetector HDF5

---

filestore/handlers.py

BUG: Fixed return from call

---

filestore/handlers.py
filestore/test/test_handlers.py

@danielballan 
This is starting to put your _lazier_ HDF5 handler into filestore. Not sure if this should be an option or just the default. Testing now.

ENH: Make HDF5 handler lazy

---

filestore/test/test_fs.py
filestore/utils.py

Also need to add a test to make sure that I hit this code path

WIP: Fix typo

---

filestore/core.py
filestore/core_v0.py
filestore/fs.py
filestore/test/conftest.py
filestore/test/test_fs.py
filestore/test/test_fs_mutate.py
filestore/test/utils.py

This a precursor for a header -> resource api in databroker.
This is on the critical path to moving files around.

Enh get resource api

---

filestore/core.py
filestore/fs.py

for use in https://github.com/NSLS-II/databroker/pull/76

ENH: Add ability to get datums for resource to public API

---

filestore/handlers.py

ENH: add TIFF handler

---

filestore/fs.py

Support exporting off of a read only filestore

Support exporting
