NSLS-II/filestore

- filestore/commands.py
The call
insert_resource('spec', None)
makes it explicit that spec does not use an actual file.
> API: Accept None as resource_path.

- filestore/api.py
- filestore/commands.py
- filestore/file_readers.py
- filestore/retrieve.py
- filestore/test/test_commands.py
- filestore/test/test_handlers.py
This adds a handler to read area detector data in the format spec implemented by @stuwilkins and dubbed 'AD_HDF5'.
The reader is called `HDF5DatasetSliceHandler`, meaning to suggest that it slices into a single Dataset in an HDF5 file. The dataset name, `'/entry/data/data/'`, is hard-coded.
@stuwilkins Instead of hard-coding the dataset name, could your insertion code pass it to `__init__`? Also, it seems that `frame_per_point` is not used. Should that be removed from the `__init__`.
> ENH: Add handler for AreaDetector data.

- filestore/commands.py
- filestore/test/test_commands.py
- filestore/utils/testing.py
- setup.py
Now tests can easily create clean, temporary databases like so:
from filestore.utils.testing import fs_setup, fs_teardown
def setup():
fs_setup()
def teardown():
fs_teardown()
There is a cousin PR in metadata store. Broker can use them both, hence the names `fs_setup` and `mds_setup`.
> API: Add fs_setup and fs_teardown testing utilities.

- setup.py
The dataportal Travis builds broke because filestore was not declaring its jsonschema dependency (or in fact any dependencies).
> BLD: Add setup.py requires.

- .travis.yml
- conda-recipe/meta.yaml
- filestore/handlers.py
Added while XPD because the HDF5 files from the HDF5 handler are mysteriously 500X larger than we expect.
This works in the wild, but has no unit tests at this time. Since it's easy enough to write tests using programmatically-generated TIFFs, we should add unit tests before merging.
> ENH: Add AreaDetectorTiffHandler

- filestore/commands.py
This can be a problem if reading configuration from ENVs
> FIX: cast port number to int

- filestore/commands.py
- filestore/retrieve.py
- filestore/test/test_commands.py
- filestore/test/test_retrieve.py
This speeds up datum retival by a factor of 30 by greedily caching
the datum documents the first time we see a resource.  By doing this
we greatly reduce the number of sockets that need to be created.
This changes the internal api of Retrive to no longer take mongoengine
documents.  This should not matter as the public API is un-changed.
> PRF/API: speed up retrieve

- filestore/handlers.py
If the handler is created before all of the individual files are
written do disk the glob will only know about the files that existed at
Handler creation time.  Before raising, this tries to re-glob the files.
closes #65
> FIX: try to refresh file list before failing

- .travis.yml
- filestore/retrieve.py
- filestore/test/test_retrieve.py
Fixes issues with development workflow of redefining and then
re-registering a handler class.
attn @ericdill
> FIX: clear handler cache on handler deregistration

- conda-recipe/meta.yaml
conda build master is now using a two-pass jinja system which means
that environ should be accessed via .get() instead of [] if you want
to access GIT_* variables.
> BLD: Use .get() instead of directly accessing env

- filestore/__init__.py
- filestore/path_only_handlers.py
- filestore/test/test_handlers.py
How many times have we wanted to just see the resource/datum documents? Coupled with https://github.com/NSLS-II/databroker/pull/37 you can do:
```python
from filestore import RawHandler
get_images(hdr, 'image', handler_override=RawHandler)
```
> ENH: Add RawHandler for debugging

- filestore/path_only_handlers.py
My original test on `RawHandler` was a little too contrived. This revision should make `RawHandler` work everywhere in the wild.
> FIX: RawHandler did not accept filepath positional arg.

- .travis.yml
- docs/source/FEP/FEP01.rst
- docs/source/FEP/index.rst
- docs/source/FEP/template.rst
- docs/source/index.rst
- filestore/api.py
- filestore/core.py
- filestore/core_v0.py
- filestore/file_writers.py
- filestore/fs.py
- filestore/handlers.py
- filestore/test/test_fs.py
- filestore/test/test_fs_mutate.py
- filestore/test/test_handlers.py
- filestore/test/utils.py
- filestore/utils.py
Obviously a major work in progress
> DOC: start to document what needs to be done to move files around

- filestore/fs.py
- filestore/test/test_fs.py
Instead of looking at the version the code thinks it is running, look at
the type used to access the resource cache.  The decides how the
resource is searched for (v0 uses _id, v1 used uid).
> FIX: major bug in handling of existing FS entries

- filestore/test/test_fs.py
I merged #101 and then #103 without giving Travis time to re-run tests on #103 rebased on #101. This fixes the problem. No production code is affected -- just the test -- so v0.4.1 is fine.
> TST: missing import

- filestore/core.py
Minor change which could (?) allow parallel inserts with mongo. Indices should take care of the ordering upon insert.
> MNT: use unordered bulk inserts

- filestore/handlers.py
'TIFF' might not be the best name, so 'SINGLE_TIFF'. See #117
> ENH: rename 'TIFF' to 'SINGLE_TIFF'

- filestore/fs.py
For https://github.com/NSLS-II/databroker/pull/88
tl;dr `Broker.get_resource_uids` currently works on with `FileStoreMoving`. This change makes it work with `FileStore`. It does *not* move any dangerous file-moving code up into `FileStore`.
> MNT: Make resource_given_eid available on base FileStore.

- doc/source/release-notes.rst
- filestore/fs.py
- filestore/test/test_fs_mutate.py
Previously this would raise a very obscure error or maybe work (but
do the wrong thing).
attn @CJ-Wright
> API: raise if trying to copy resource without root

- filestore/handlers.py
We're using this. Even if this isn't worth pulling, input would be appreciated!
Have not written a test but we tested it on our analysis store.
I assume that this well loved vague file extension can be read to `np.loadtxt` with the proper args. I think it's reasonable?
note: `delimiter=","` loads csv files
@danielballan @licode
> added DAT handler

- filestore/fs.py
Fix a key error during export, root can not exist at which point it is `None`.
> FIX: fix key error during export
